name: push on dev

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with: 
          node-version: 18
        working-directory: ./ecommerce-experiment.client
      - run: npm ci
      - run: npm test
      - run: npm run build
      - run: npm run dev
