name: push on dev

on:
  push:
    branches:
      - 'dev'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: pnpm dep install & test
        working-directory: ./ecommerce-experiment.client
        run: |
          pnpm i
          pnpm run build
  merge-branch:
    name: Merge dev into main
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      pull-requests: write
      issues: write
      contents: write
    if: needs.build.result == 'success'
    steps:
      - uses: actions/checkout@v3
      - uses: diillson/auto-pull-request@v1.0.1
        with:
          source_branch: ${{ github.ref }} 
          destination_branch: 'main'
          github_token: ${{ github.token }}
          pr_title: '[Automated] Pulling ${{ github.ref }} into main'
          pr_body: |
            **Only succeeds if all tests and the build were successful**
    
